input:
  path: 'data\input'
  recursive: false
  allowed_extensions:
    - ".mp4"
    - ".avi"
    - ".mov"
    - ".mkv"

output:
  directory: "./data/output"

segmentation:
  enabled: true
  segment_duration_seconds: 600

sampling:
  every_n_frames: 50
  every_n_seconds: null

processing:
  diff_threshold: 25
  blur_kernel_size: 5
  active_motion_threshold: 0.02

logging:
  level: "INFO"
  progress_update_seconds: 30
